### ISSUE TITLE
Doesn't work with `.css.liquid` files

### ISSUE THREAD

**Issue by haotan19** [Shopify/prettier-plugin-liquid#105]
**Describe the bug**

**Unformatted source**
```css
.countdown-timer {
  width: 360px;
  max-width: 100%;
  margin: 0 auto 20px;
}
.countdown-item__num {
  border-radius: 10px;
  background-color: #131313;
  color: #ffffff;
}
```

**Expected output**
```css
.countdown-timer {
  width: 360px;
  max-width: 100%;
  margin: 0 auto 20px;
}
.countdown-item__num {
  border-radius: 10px;
  background-color: #131313;
  color: #ffffff;
}
```

**Actual output**
```css
.countdown-timer { width: 360px; max-width: 100%; margin: 0 auto 20px; }
.countdown-item__num { border-radius: 10px; background-color: #131313; color:
#ffffff; }
```

**Debugging information**
 - OS: Windows 11
 - Version 0.4.0

**Comment by charlespwd** [comment]
We should be clearer that we have no intention of supporting this (since this is a LiquidHTML prettier plugin). 

Our recommendation is the following:
- Define [CSS Custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) somewhere in your HTML-Liquid files.
- Use plain `.css` files that refer to those custom CSS properties

Example:

`theme.liquid`
```liquid
<style>
  :root {
    --accent-colour: {{ some_setting }};
  }
</style>
```

`styles.css`
```css
button.accent {
  color: var(--accent-colour);
}
```

You can see this pattern used in the Dawn repo. 
- [theme.liquid](https://github.com/Shopify/dawn/blob/main/layout/theme.liquid#L48-L184)
- [base.css](https://github.com/Shopify/dawn/blob/main/assets/base.css#L3-L14)

Pros of this approach:
- Your CSS files are then true CSS files. This means you can use the official syntax highlighting for CSS, the formatter for CSS, etc. Which are bound to have better support that this plugin can offer. 
- You can use build tools independently of Liquid that work with CSS files.
- You could even use LESS or SCSS independently if you are so inclined.
